# properteis --> yaml

server:
  port: 8080

spring:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        show_sql: false 
    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/zari?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: test
    password: jsr
